server:
  port: 9190

#resilience4j:
#  circuitbreaker:
#    instances:
#      userService:
#        registerHealthIndicator: true
#        eventConsumerBufferSize: 10
#        failureRateThreshold: 50
#        minimumNumberOfCalls: 5
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        waitDurationInOpenState: 5s
#        permittedNumberOfCallsInHalfOpenState: 3
#        slidingWindowSize: 10
#        slidingWindowType: COUNT_BASED

resilience4j:
  retry:
    instances:
      userService:
#        Ideal Condition
#        maxRetryAttempts: 3
#        waitDuration: 2s
        maxRetryAttempts: 5
        waitDuration: 5s